### PR TITLE
refact: Color.gammaToLinearSpace to improve performance, speed increased by 7 times.

### PR DESCRIPTION
**Pull request by chenyunda218**
### Please check if the PR fulfills these requirements

- [x] The commit message follows our [guidelines](https://github.com/galacean/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
refactor function for enhance performance.
### What is the current behavior? (You can also link to an open issue here)
Color.gammaToLinearSpace is so many branch cause break cpu Branch predictor.
### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
There is about 3e-11 in the precision of floating point numbers between two version.

## Summary by CodeRabbit

- **New Features**
	- Introduced new static properties for improved color calculations.
	- Added a `sigmoid` method for normalizing values between 0 and 1.
- **Improvements**
	- Enhanced the `gammaToLinearSpace` method for more efficient calculations, eliminating previous conditional checks.

### CODE REVIEW

**Comment by GuoLei1990** [comment]
The PR has lint errors, you can fix them with `lint --fix`

**Comment by chenyunda218** [comment]
> The PR has lint errors, you can fix them with `lint --fix`

Thanks, I've fixed it.

**Comment by GuoLei1990** [comment]
After detailed testing, it was found that this PR actually caused performance degradation. The case is as follows:
https://jsbench.me/vqm2u50u6r/1
Can you confirm whether it can be improved?

We are happy for you to submit PRs and hope you can continue to contribute！

**Comment by chenyunda218** [comment]
After my testing. it depending on runtime. In nodejs the new one faster. In chrome same. Other runtime is slower. So i think it is not a good refactor.
Apologize for my negligence.

**Pull request closed without merging**
