### PR TITLE
Feat: prefab additive modifications

### PR DESCRIPTION
**Pull request by luzhuang**
### Please check if the PR fulfills these requirements

- [x] The commit message follows our [guidelines](https://github.com/galacean/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Test Project: [playground-prefab.zip](https://github.com/galacean/engine/files/12246436/playground-prefab.zip)

link: https://github.com/galacean/engine/pull/1601

### CODE REVIEW

**Comment by gz65555** [comment]
There are some cases cannot be passed.

**Comment by gz65555** [comment]
We should design some test cases for these pull request first.

**Comment by gz65555** [comment]
This is my test case. Supposed that a cuboid in the center of screen.
[simple-prefab.zip](https://github.com/galacean/engine/files/12297723/simple-prefab.zip)

**Comment by luzhuang** [comment]
> This is my test case. Supposed that a cuboid in the center of screen. [simple-prefab.zip](https://github.com/galacean/engine/files/12297723/simple-prefab.zip)

[playground-prefab 2.zip](https://github.com/galacean/engine/files/12308645/playground-prefab.2.zip)
the newest demo and fixed some issue and  add stripped function

**Pull request closed without merging**
