### PR TITLE
Fix pack physics miniprogram error

### PR DESCRIPTION
**Pull request by cptbtptpbcptdtptp**

### CODE REVIEW

**Comment by YunYouJun** [comment]
What's your pnpm version?

**Comment by cptbtptpbcptdtptp** [comment]
> What's your pnpm version?

8.6.0

**Comment by YunYouJun** [comment]
You can upgrade pnpm package version to be same with yours here.

https://github.com/galacean/engine/blob/69023fe5c138bd80b0f7c8a98cc68fd8e51b0912/package.json#L4

**Comment by cptbtptpbcptdtptp** [comment]
> You can upgrade pnpm package version to be same with yours here.
> 
> https://github.com/galacean/engine/blob/69023fe5c138bd80b0f7c8a98cc68fd8e51b0912/package.json#L4

Done.

**Comment by YunYouJun** [comment]
For reference, pnpm@8.6.2 change lockfile version back to `6.0`.

https://github.com/pnpm/pnpm/releases/tag/v8.6.2

**Review by YunYouJun — APPROVED** [review]

**Review by GuoLei1990 — APPROVED** [review]

**Pull request merged**
