### PR TITLE
Fix text error for set text to "" and set enableWrapping to true

### PR DESCRIPTION
**Pull request by singlecoder**
…o true

### Please check if the PR fulfills these requirements

- [ ] The commit message follows our [guidelines](https://github.com/galacean/engine/blob/main/.github/COMMIT_MESSAGE_CONVENTION.md)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by cptbtptpbcptdtptp — APPROVED** [review]
+1

**Review by jtabibito — COMMENTED** [review]
Test passed.

**Review by jtabibito — COMMENTED** [review]
+1

**Review by jtabibito — APPROVED** [review]

**Review by GuoLei1990 — CHANGES_REQUESTED** [review]
Add unit test when text is "" and error

**Review by GuoLei1990 — APPROVED** [review]

**Pull request merged**
